---

- name: install python pkgs
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - libpq-dev
    - python3
    - python3-dev
    - python-pip
    - python-virtualenv
    - git


- name: setup virtualenv
  sudo: no
  pip: >
      requirements={{ BASE_DIR }}/requirements.txt
      virtualenv={{ BASE_DIR }}/venv
      virtualenv_command="virtualenv -p/usr/bin/python3"

- name: install HELPeR
  sudo: no
  pip: >
      name='-e {{ BASE_DIR }}'
      virtualenv={{ BASE_DIR }}/venv
      virtualenv_command="virtualenv -p/usr/bin/python3"

- name: make project
  sudo: no
  command: '{{ BASE_DIR }}/venv/bin/django-admin.py startproject --template={{ BASE_DIR }}/helper/conf/project_template project {{ BASE_DIR }}'
  args:
    creates: '{{ BASE_DIR }}/manage.py'
