---
- name: migrate & collectstatic
  sudo_user: "{{ USER }}"
  django_manage: >
      command={{ item }}
      app_path={{ BASE_DIR }}
      virtualenv={{ BASE_DIR }}/venv
  with_items:
    - migrate
    - collectstatic

- name: supervisor config
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/helper-app.conf
  notify:
    - reload supervisor
